apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      tier: db
  template:
    metadata:
      labels:
        app: mongo
        tier: db
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          # env:
          #   - name: MONGO_INITDB_ROOT_USERNAME
          #     value: root
          #   - name: MONGO_INITDB_ROOT_PASSWORD
          #     value: root