apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-service
spec:
  ports:
  - port: 8888
    targetPort: 3000
    protocol: TCP
    name: http-server
  type: LoadBalancer
  selector:
    app: {{.Chart.Name}}